### ISSUE TITLE
Add possibility to prepend the link's href

### ISSUE THREAD

**Issue by dsebastien** [rehypejs/rehype-autolink-headings#9]
### Subject of the feature

It would be nice to be able to prepend the generated links with a custom string. In my case, I'd like to use the complete page's URL before the hash.

### Problem

I'm facing the following error with Next.js, which I don't understand very clearly: https://github.com/vercel/next.js/blob/master/errors/href-interpolation-failed.md

I suppose that it's quite specific to Next.js, but I feel like being able to prepend the href with the current page's full URL should solve my issue.

### Expected behavior

Ability to define a prefix string for the href.

### Alternatives

None

**Comment by wooorm** [comment]
Prefixes when we’re talking about about headings typically implies using `user-content-` or so, which is what GH does, not prevent DOM clobbering with user-generated content. Here’s the HTML they use for the Install heading in the readme:

```
<h2><a id="user-content-install" class="anchor" aria-hidden="true" href="#install"><svg ...></svg></a>Install</h2>
```

---

You are asking for something that can’t be properly solved in this plugin. Sure, it could fix this for headings, but it’d fail if you’d place an actual link: `[link to heading](#heading)`: that would also not work, right?

So then maybe you need to rewrite all your relative URLs in markdown. And you can make your own plugin for that. Here’s one that shows the gist of how it works, but is otherwise more complex that what you need: https://github.com/unifiedjs/unifiedjs.github.io/blob/main/generate/plugin/rehype-rewrite-urls.js.

Still, I think you’re asking about an [XY problem](https://xyproblem.info). I don’t easily see how that error related to this plugin.

**Comment by wooorm** [comment]
I think this is better solved somewhere else
